-- ==========================================
-- AYUSCHOLAR QUIZ BOT — DATABASE INITIALIZATION SCRIPT
-- Copy and paste this script into your Supabase SQL Editor
-- (Database -> SQL Editor -> New Query -> Paste -> Run)
-- ==========================================

-- 1. Create target Telegram Groups table
CREATE TABLE IF NOT EXISTS public.groups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    handle TEXT UNIQUE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Create Scheduler settings table
CREATE TABLE IF NOT EXISTS public.settings (
    id BIGINT PRIMARY KEY DEFAULT 1,
    post_times TEXT[] NOT NULL DEFAULT ARRAY['10:00', '21:00']::text[],
    folder1_questions INT NOT NULL DEFAULT 1,
    folder2_questions INT NOT NULL DEFAULT 1,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    CONSTRAINT single_row CHECK (id = 1) -- Enforces only one configuration row
);

-- 3. Create Folder progress tracking table
CREATE TABLE IF NOT EXISTS public.progress (
    folder_name TEXT PRIMARY KEY CHECK (folder_name IN ('folder1', 'folder2')),
    current_file_index INT NOT NULL DEFAULT 0,
    used_indices INT[] NOT NULL DEFAULT '{}'::int[],
    total_posted INT NOT NULL DEFAULT 0,
    cycles INT NOT NULL DEFAULT 0,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. Create Posting Logs table
CREATE TABLE IF NOT EXISTS public.logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_label TEXT NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('success', 'failed')),
    details TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ==========================================
-- SEED DEFAULT DATA
-- ==========================================

-- Seed default scheduler row
INSERT INTO public.settings (id, post_times, folder1_questions, folder2_questions)
VALUES (1, ARRAY['10:00', '21:00']::text[], 1, 1)
ON CONFLICT (id) DO NOTHING;

-- Seed default Telegram groups
INSERT INTO public.groups (handle)
VALUES 
    ('@aiapgetexam'),
    ('@tmayu'),
    ('@ayuscholaraiapget')
ON CONFLICT (handle) DO NOTHING;

-- Seed default progress states
INSERT INTO public.progress (folder_name, current_file_index, used_indices, total_posted, cycles)
VALUES 
    ('folder1', 0, '{}'::int[], 0, 0),
    ('folder2', 0, '{}'::int[], 0, 0)
ON CONFLICT (folder_name) DO NOTHING;

-- ==========================================
-- ENABLE REAL-TIME CAPABILITIES (Optional but recommended)
-- ==========================================
ALTER publication supabase_realtime ADD TABLE public.settings;
ALTER publication supabase_realtime ADD TABLE public.progress;
ALTER publication supabase_realtime ADD TABLE public.groups;
ALTER publication supabase_realtime ADD TABLE public.logs;

-- ==========================================
-- STORAGE BUCKETS INSTRUCTIONS
-- ==========================================
-- Standard SQL can't create storage buckets directly without complex API calls.
-- Please perform this quick 20-second setup in the Supabase Dashboard:
-- 1. Go to "Storage" in the left sidebar.
-- 2. Click "New Bucket".
-- 3. Name the bucket EXACTLY: quiz-sheets
-- 4. Keep the bucket PRIVATE (public toggle OFF). This is secure!
-- 5. Inside the bucket, create two folders: folder1 and folder2
--    (You can create them through the Dashboard, or upload files directly into them using the Dashboard, or use our Admin Web Control Panel to automatically upload files!)
